global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: "production"
    region: "ir-tehran-1"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "telecom-host"

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx-exporter:9113"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "telecom-service"
